'use server';
/**
 * @fileOverview A friendly chatbot to assist users with the KONTROLA app.
 *
 * - askKontrola - A function that answers user questions about the app.
 * - AskKontrolaInput - The input type for the flow.
 * - AskKontrolaOutput - The output type for the flow.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';

export const AskKontrolaInputSchema = z.object({
  question: z.string().describe("The user's question about the app."),
});
export type AskKontrolaInput = z.infer<typeof AskKontrolaInputSchema>;

export const AskKontrolaOutputSchema = z.object({
  answer: z
    .string()
    .describe('A helpful and friendly answer to the user question.'),
});
export type AskKontrolaOutput = z.infer<typeof AskKontrolaOutputSchema>;

export async function askKontrola(
  input: AskKontrolaInput
): Promise<AskKontrolaOutput> {
  return askKontrolaFlow(input);
}

const prompt = ai.definePrompt({
  name: 'askKontrolaPrompt',
  input: { schema: AskKontrolaInputSchema },
  output: { schema: AskKontrolaOutputSchema },
  prompt: `You are "Ask", a friendly and helpful AI assistant for the KONTROLA financial management app. Your goal is to assist users by answering their questions about the app's features and how to use them.

App Features:
- Dashboard: Overview of finances.
- Income/Expenses: Track money coming in and going out.
- Budgets: Set spending limits for categories. (Premium feature)
- Bills: Track upcoming payments and get reminders. (Premium feature)
- Goals: Set and track savings goals. (Premium feature)
- Reports: Analyze financial data and export reports. (Premium feature)
- Kontrola Score: A proprietary score representing your financial health.
- AI Advisor: Get personalized financial insights generated by AI.
- Business Dashboard: For Pro Plus users to manage business finances, customers, and invoices.
- Settings: Manage profile, preferences, and link bank/mobile money accounts.
- Market List: Create and manage shopping lists for market trips.

Based on the user's question, provide a clear, concise, and friendly answer. If the question is outside the scope of the KONTROLA app, politely state that you can only help with app-related queries.

User's Question:
{{{question}}}
`,
});

const askKontrolaFlow = ai.defineFlow(
  {
    name: 'askKontrolaFlow',
    inputSchema: AskKontrolaInputSchema,
    outputSchema: AskKontrolaOutputSchema,
  },
  async (input) => {
    const { output } = await prompt(input);
    return output!;
  }
);
