'use server';
/**
 * @fileOverview A friendly chatbot to assist users with the KONTROLA app.
 *
 * - askKontrola - A function that answers user questions about the app.
 * - AskKontrolaInput - The input type for the flow.
 * - AskKontrolaOutput - The output type for the flow.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';

export const AskKontrolaInputSchema = z.object({
  question: z.string().describe("The user's question about the app."),
});
export type AskKontrolaInput = z.infer<typeof AskKontrolaInputSchema>;

export const AskKontrolaOutputSchema = z.object({
  answer: z
    .string()
    .describe('A helpful and friendly answer to the user question.'),
});
export type AskKontrolaOutput = z.infer<typeof AskKontrolaOutputSchema>;

export async function askKontrola(
  input: AskKontrolaInput
): Promise<AskKontrolaOutput> {
  return askKontrolaFlow(input);
}

const prompt = ai.definePrompt({
  name: 'askKontrolaPrompt',
  input: { schema: AskKontrolaInputSchema },
  output: { schema: AskKontrolaOutputSchema },
  model: 'googleai/gemini-2.5-flash',
  prompt: `You are "Ask", a friendly and helpful 24/7 AI support assistant for the KONTROLA financial management app. Your primary goal is to provide instant, clear, and concise help to users by answering their questions about the app's features and how to use them effectively.

App Features:
- Dashboard: Overview of finances.
- Income/Expenses: Track money coming in and going out.
- Budgets & Planning: Create budgets for spending categories and plan your shopping with the Market List. (Budgets are a Premium feature)
- Bills: Track upcoming payments and get reminders. (Premium feature)
- Savings Goals: Set personal savings goals or join a "Save Go" savings challenge to build your habits. (Premium feature)
- Reports: Analyze financial data with charts and export reports to PDF/Excel. (Exporting is a Premium feature)
- Kontrola Score: A proprietary score from 0-1000 representing your financial health, based on your habits.
- AI Advisor: Get personalized financial insights generated by AI.
- Business Dashboard: For Pro Plus users, manage business finances, customers, invoices, and receipts.
- Settings: Manage your profile, language/currency preferences, and link bank/mobile money accounts for auto-sync.

Based on the user's question, provide a clear, concise, and friendly answer. If the question is outside the scope of the KONTROLA app, politely state that you can only help with app-related queries.

User's Question:
{{{question}}}
`,
});

const askKontrolaFlow = ai.defineFlow(
  {
    name: 'askKontrolaFlow',
    inputSchema: AskKontrolaInputSchema,
    outputSchema: AskKontrolaOutputSchema,
  },
  async (input) => {
    const { output } = await prompt(input);
    return output!;
  }
);
